dist: xenial

language: python

python:
- 3.4
- 3.5
- 3.6
- 3.7

install:
- pip install blink1
- pip install lifxlan
- pip install phue
- pip install requests
- pip install yeelight
- pip install coveralls
- pip install requests
- pip install pylint
- pip install pytest
- pip install pytest-cov
- pip install pytest-mock
- pip install mock

script:
- pylint bin/chroma-feedback chroma_feedback tests
- pytest tests --cov=chroma_feedback

after_success:
- coveralls