version: 2

jobs:
 lint:
  docker:
  - image: circleci/python:3.6.6-stretch-browsers
  steps:
  - checkout
  - run: sudo pip install requests pylint pytest pytest-mock mock
  - run: pylint bin/chroma-feedback src tests
 test:
  docker:
  - image: circleci/python:3.6.6-stretch-browsers
  steps:
  - checkout
  - run: sudo pip install requests pylint pytest pytest-mock mock
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test