version: 2

jobs:
 lint:
  docker:
  - image: circleci/python:3.6.6-stretch-browsers
  steps:
  - checkout
  - run: pip install coveralls
  - run: pip install requests
  - run: pip install pylint
  - run: pip install pytest
  - run: pip install pytest-cov
  - run: pip install pytest-mock
  - run: pip install mock
  - run: pylint bin/chroma-feedback chroma_feedback tests
 test:
  docker:
  - image: circleci/python:3.6.6-stretch-browsers
  steps:
  - checkout
  - run: pip install coveralls
  - run: pip install requests
  - run: pip install pylint
  - run: pip install pytest
  - run: pip install pytest-cov
  - run: pip install pytest-mock
  - run: pip install mock
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test